config/routes.rb
Rails.application.routes.draw do
  resources :reservas
  resources :hotels
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/hotelarium.rb
class Hotelarium < ApplicationRecord
end

app/models/reserva.rb
class Reserva < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:nome, :endereco)
    end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: %i[ show edit update destroy ]

  # GET /reservas or /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1 or /reservas/1.json
  def show
  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
  end

  # POST /reservas or /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: "Reserva was successfully created." }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1 or /reservas/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: "Reserva was successfully updated." }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1 or /reservas/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: "Reserva was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reserva_params
      params.require(:reserva).permit(:hospede, :quarto, :hotel, :data_da_reserva, :fim_da_reserva)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/hotels/_form.html.erb
<%= form_for @hotel, :html => { :class => "form-horizontal hotel" } do |f| %>

  <% if @hotel.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @hotel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :endereco, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :endereco, :class => 'form-control' %>
    </div>
    <%=f.error_span(:endereco) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                hotels_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/hotels/edit.html.erb
<%- model_class = Hotel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/hotels/index.html.erb
<%- model_class = Hotel -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:endereco) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= link_to hotel.id, hotel_path(hotel) %></td>
        <td><%= hotel.nome %></td>
        <td><%= hotel.endereco %></td>
        <td><%=l hotel.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_hotel_path(hotel), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      hotel_path(hotel),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_hotel_path,
            :class => 'btn btn-primary' %>

app/views/hotels/new.html.erb
<%- model_class = Hotel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/hotels/show.html.erb
<%- model_class = Hotel -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @hotel.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:endereco) %>:</strong></dt>
  <dd><%= @hotel.endereco %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              hotels_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_hotel_path(@hotel), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              hotel_path(@hotel),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hotelaria1" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Hotelaria1</a>
        
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Hotel", "/hotels"  %></li>   
              <li><%= link_to "Reservas", "/reservas"  %></li>      
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; UESPI 2021</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/reservas/_form.html.erb
<%= form_for @reserva, :html => { :class => "form-horizontal reserva" } do |f| %>

  <% if @reserva.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@reserva.errors.count, "error") %> prohibited this reserva from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @reserva.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :hospede, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :hospede, :class => 'form-control' %>
    </div>
    <%=f.error_span(:hospede) %>
  </div>
  <div class="form-group">
    <%= f.label :quarto, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :quarto, :class => 'form-control' %>
    </div>
    <%=f.error_span(:quarto) %>
  </div>
  <div class="form-group">
    <%= f.label :hotel, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :hotel, :class => 'form-control' %>
    </div>
    <%=f.error_span(:hotel) %>
  </div>
  <div class="form-group">
    <%= f.label :data_da_reserva, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :data_da_reserva, :class => 'form-control' %>
    </div>
    <%=f.error_span(:data_da_reserva) %>
  </div>
  <div class="form-group">
    <%= f.label :fim_da_reserva, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :fim_da_reserva, :class => 'form-control' %>
    </div>
    <%=f.error_span(:fim_da_reserva) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reservas_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/reservas/edit.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reservas/index.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:hospede) %></th>
      <th><%= model_class.human_attribute_name(:quarto) %></th>
      <th><%= model_class.human_attribute_name(:hotel) %></th>
      <th><%= model_class.human_attribute_name(:data_da_reserva) %></th>
      <th><%= model_class.human_attribute_name(:fim_da_reserva) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= link_to reserva.id, reserva_path(reserva) %></td>
        <td><%= reserva.hospede %></td>
        <td><%= reserva.quarto %></td>
        <td><%= reserva.hotel %></td>
        <td><%= reserva.data_da_reserva %></td>
        <td><%= reserva.fim_da_reserva %></td>
        <td><%=l reserva.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_reserva_path(reserva), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      reserva_path(reserva),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_reserva_path,
            :class => 'btn btn-primary' %>

app/views/reservas/new.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reservas/show.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:hospede) %>:</strong></dt>
  <dd><%= @reserva.hospede %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quarto) %>:</strong></dt>
  <dd><%= @reserva.quarto %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hotel) %>:</strong></dt>
  <dd><%= @reserva.hotel %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data_da_reserva) %>:</strong></dt>
  <dd><%= @reserva.data_da_reserva %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fim_da_reserva) %>:</strong></dt>
  <dd><%= @reserva.fim_da_reserva %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              reservas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reserva_path(@reserva), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              reserva_path(@reserva),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>